### PR TITLE
A: https://www.flashscore.se/

### PR DESCRIPTION
**Pull request by hkarn**

### CODE REVIEW

**Comment by KrisGalcz** [comment]
I can't reproduce it. Could you add a link to subpage?

**Comment by hkarn** [comment]
Yes there is no ad in that position anymore even with adblock completely off. Maybe we leave it a couple of days and check again before closing this?

image

**Comment by KrisGalcz** [comment]
Sure, it can stay here

**Comment by hkarn** [comment]
It is back.
image

**Pull request merged**
