### PR TITLE
Happyride.se

### PR DESCRIPTION
**Pull request by hkarn**

### CODE REVIEW

**Comment by KrisGalcz** [comment]
In the second commit this would be enough:
happyride.se#?#img[src^="/img/sponsor/"]
#?# filters are slower and doesn't work on mobile, so if there is possibility to avoid it, it's better to do so

**Comment by monzta** [comment]
I agree with Kris. Maybe you can just block the images instead?

**Comment by hkarn** [comment]
Yes, added a block rule instead. 
There is also a potential issue with EasyList on this site. It blocks images in /admarket/*
which appear to block all images inside this sites own classified ads system, which probably shouldn't be blocked...

**Comment by KrisGalcz** [comment]
Hey hkran.
If there is a generic filter like that which is blocking something on Scandinavian site then you can add exception rule on your list. Eg.
@@/genericfilter/*$domain=example.com

**Pull request merged**
