### PR TITLE
A: https://nt.se/nyheter/

### PR DESCRIPTION
**Pull request by hkarn**

### CODE REVIEW

**Comment by KrisGalcz** [comment]
It looks like they changed page so hiding filters don't work anymore

**Comment by KrisGalcz** [comment]
I don't see any hits from this filter, do you use any VPN?

**Comment by hkarn** [comment]
No but it appears something changed on all the sites that filter applied to and it is no longer relevant.

**Comment by hkarn** [comment]
Re-added lystra filter. It is hiding cinema ads (BIO) at the bottom of the page. the iframe is dynamically loaded so the tags didnt appear on scanning raw page source.

2019-05-30 21_57_40-Window

**Comment by KrisGalcz** [comment]
Now I see it

**Pull request merged**
