### PR TITLE
A: https://www.svenskamagic.com/forumet/

### PR DESCRIPTION
**Pull request by hkarn**
Occasional self-promotion can be hidden svenskamagic.com###reklam but the main purpose of the column seems to be to display foreign ads on the side. Reklam means ads

### CODE REVIEW

**Comment by KrisGalcz** [comment]
Hey. It looks like discordapp.com is delivering widget, which could be users for user forum (It's allowing them to call each other as I understand) and it's in id "reklam"

**Comment by KrisGalcz** [comment]
Accidentally I deleted filter `ekuriren.se##iframe[id^=lystra]` during merging. Could you add it again with next pull request?

**Comment by hkarn** [comment]
Yes, they are using it for self-promotion. But they are also selling ad-free subscriptions which hides all of this self-promotion to there store and the discordapp widget so?

**Comment by KrisGalcz** [comment]
Still I would left it alone. If it's not an ad then it shouldn't be blocked

**Pull request closed without merging**
